version: '3.3'
services:
  dnsmasq:
    privileged: true
    container_name: dnsmasq
    ports:
      - '53:53/udp'
    volumes:
      - '/share/Container/repo/dnsmasq.conf:/etc/dnsmasq.conf'
    logging:
      options:
        max-size: 100m
    restart: always
    image: anzevalher/dnsmasq:latest
    network_mode: "host"
    cap_drop:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SETUID
      - SETGID
