version: '3.3'
services:
  dnsmasq:
    privileged: true
    container_name: dnsmasq
    ports:
      - '6000:53/udp'
    volumes:
      - '/share/Container/repo/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf'
    logging:
      options:
        max-size: 100m
    restart: always
    image: anzevalher/dnsmasq:latest
    cap_drop:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SETUID
      - SETGID
    networks:
      - "dns"
networks:
  dns:
    driver: bridge
